// shared/constants/errorCodes.js

module.exports = {
  // General
  INVALID_INPUT: "INVALID_INPUT",
  NOT_FOUND: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  REQUIRED_FIELDS_MISSING: "REQUIRED_FIELDS_MISSING",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  OLD_PASSWORD_INCORRECT: "OLD_PASSWORD_INCORRECT",
  RIDER_ALREADY_APPROVED: "RIDER_ALREADY_APPROVED", 
  // OTP
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",

  // Token
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  INVALID_TOKEN: "INVALID_TOKEN",

  // Restaurant
  RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",
  RESTAURANT_EMAIL_EXISTS: "RESTAURANT_EMAIL_EXISTS",
  RESTAURANT_PHONE_EXISTS: "RESTAURANT_PHONE_EXISTS",
  TAX_ID_EXISTS: "TAX_ID_EXISTS",
  BUSINESS_LICENSE_EXISTS: "BUSINESS_LICENSE_EXISTS",

  // Store
  STORE_NOT_FOUND: "STORE_NOT_FOUND",
  STORE_EMAIL_EXISTS: "STORE_EMAIL_EXISTS",
  STORE_PHONE_EXISTS: "STORE_PHONE_EXISTS",

  // File Upload
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  TOO_MANY_FILES: "TOO_MANY_FILES",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",

  // Job Matching
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  RESUME_NOT_FOUND: "RESUME_NOT_FOUND",
  EMBEDDING_GENERATION_FAILED: "EMBEDDING_GENERATION_FAILED",
  EXPLANATION_GENERATION_FAILED: "EXPLANATION_GENERATION_FAILED",
  RESUME_PARSING_FAILED: "RESUME_PARSING_FAILED",
  NO_RESUMES_FOUND: "NO_RESUMES_FOUND",
  NO_JOBS_FOUND: "NO_JOBS_FOUND",
  INVALID_RESUME_FORMAT: "INVALID_RESUME_FORMAT",
  FORBIDDEN_RESUME_ACCESS: "FORBIDDEN_RESUME_ACCESS",
};
